sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    access-key-secret: EWE0lUzc4uYza7d6Zcie1unFYXwuB2
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: sky-out-obscur
    access-key-id: LTAI5t6YQYFH7ZURQkh7NQmc
  redis:
    data:
      host: localhost
      port: 6379
      password: 123456
      database: 0
  wechat:
    appid: wx68f50763d49154aa
    secret: 4da2e77f8c5967d60b410aa596cd1d5a